# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Dropbox/Programming/C++/AdvancedEvolutionaryTatics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Dropbox/Programming/C++/AdvancedEvolutionaryTatics

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Dropbox/Programming/C++/AdvancedEvolutionaryTatics/CMakeFiles /home/david/Dropbox/Programming/C++/AdvancedEvolutionaryTatics/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Dropbox/Programming/C++/AdvancedEvolutionaryTatics/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AET

# Build rule for target.
AET: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AET
.PHONY : AET

# fast build rule for target.
AET/fast:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/build
.PHONY : AET/fast

Body.o: Body.cpp.o
.PHONY : Body.o

# target to build an object file
Body.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Body.cpp.o
.PHONY : Body.cpp.o

Body.i: Body.cpp.i
.PHONY : Body.i

# target to preprocess a source file
Body.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Body.cpp.i
.PHONY : Body.cpp.i

Body.s: Body.cpp.s
.PHONY : Body.s

# target to generate assembly for a file
Body.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Body.cpp.s
.PHONY : Body.cpp.s

Engine.o: Engine.cpp.o
.PHONY : Engine.o

# target to build an object file
Engine.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine.cpp.o
.PHONY : Engine.cpp.o

Engine.i: Engine.cpp.i
.PHONY : Engine.i

# target to preprocess a source file
Engine.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine.cpp.i
.PHONY : Engine.cpp.i

Engine.s: Engine.cpp.s
.PHONY : Engine.s

# target to generate assembly for a file
Engine.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine.cpp.s
.PHONY : Engine.cpp.s

Engine_Event.o: Engine_Event.cpp.o
.PHONY : Engine_Event.o

# target to build an object file
Engine_Event.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Event.cpp.o
.PHONY : Engine_Event.cpp.o

Engine_Event.i: Engine_Event.cpp.i
.PHONY : Engine_Event.i

# target to preprocess a source file
Engine_Event.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Event.cpp.i
.PHONY : Engine_Event.cpp.i

Engine_Event.s: Engine_Event.cpp.s
.PHONY : Engine_Event.s

# target to generate assembly for a file
Engine_Event.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Event.cpp.s
.PHONY : Engine_Event.cpp.s

Engine_Level.o: Engine_Level.cpp.o
.PHONY : Engine_Level.o

# target to build an object file
Engine_Level.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Level.cpp.o
.PHONY : Engine_Level.cpp.o

Engine_Level.i: Engine_Level.cpp.i
.PHONY : Engine_Level.i

# target to preprocess a source file
Engine_Level.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Level.cpp.i
.PHONY : Engine_Level.cpp.i

Engine_Level.s: Engine_Level.cpp.s
.PHONY : Engine_Level.s

# target to generate assembly for a file
Engine_Level.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Level.cpp.s
.PHONY : Engine_Level.cpp.s

Engine_Resources.o: Engine_Resources.cpp.o
.PHONY : Engine_Resources.o

# target to build an object file
Engine_Resources.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Resources.cpp.o
.PHONY : Engine_Resources.cpp.o

Engine_Resources.i: Engine_Resources.cpp.i
.PHONY : Engine_Resources.i

# target to preprocess a source file
Engine_Resources.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Resources.cpp.i
.PHONY : Engine_Resources.cpp.i

Engine_Resources.s: Engine_Resources.cpp.s
.PHONY : Engine_Resources.s

# target to generate assembly for a file
Engine_Resources.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Engine_Resources.cpp.s
.PHONY : Engine_Resources.cpp.s

Entity.o: Entity.cpp.o
.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i
.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s
.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

Event.o: Event.cpp.o
.PHONY : Event.o

# target to build an object file
Event.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Event.cpp.o
.PHONY : Event.cpp.o

Event.i: Event.cpp.i
.PHONY : Event.i

# target to preprocess a source file
Event.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Event.cpp.i
.PHONY : Event.cpp.i

Event.s: Event.cpp.s
.PHONY : Event.s

# target to generate assembly for a file
Event.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Event.cpp.s
.PHONY : Event.cpp.s

Eye.o: Eye.cpp.o
.PHONY : Eye.o

# target to build an object file
Eye.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Eye.cpp.o
.PHONY : Eye.cpp.o

Eye.i: Eye.cpp.i
.PHONY : Eye.i

# target to preprocess a source file
Eye.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Eye.cpp.i
.PHONY : Eye.cpp.i

Eye.s: Eye.cpp.s
.PHONY : Eye.s

# target to generate assembly for a file
Eye.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Eye.cpp.s
.PHONY : Eye.cpp.s

Fang.o: Fang.cpp.o
.PHONY : Fang.o

# target to build an object file
Fang.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Fang.cpp.o
.PHONY : Fang.cpp.o

Fang.i: Fang.cpp.i
.PHONY : Fang.i

# target to preprocess a source file
Fang.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Fang.cpp.i
.PHONY : Fang.cpp.i

Fang.s: Fang.cpp.s
.PHONY : Fang.s

# target to generate assembly for a file
Fang.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Fang.cpp.s
.PHONY : Fang.cpp.s

Leg.o: Leg.cpp.o
.PHONY : Leg.o

# target to build an object file
Leg.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Leg.cpp.o
.PHONY : Leg.cpp.o

Leg.i: Leg.cpp.i
.PHONY : Leg.i

# target to preprocess a source file
Leg.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Leg.cpp.i
.PHONY : Leg.cpp.i

Leg.s: Leg.cpp.s
.PHONY : Leg.s

# target to generate assembly for a file
Leg.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Leg.cpp.s
.PHONY : Leg.cpp.s

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/Main.cpp.s
.PHONY : Main.cpp.s

entities/Attack.o: entities/Attack.cpp.o
.PHONY : entities/Attack.o

# target to build an object file
entities/Attack.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Attack.cpp.o
.PHONY : entities/Attack.cpp.o

entities/Attack.i: entities/Attack.cpp.i
.PHONY : entities/Attack.i

# target to preprocess a source file
entities/Attack.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Attack.cpp.i
.PHONY : entities/Attack.cpp.i

entities/Attack.s: entities/Attack.cpp.s
.PHONY : entities/Attack.s

# target to generate assembly for a file
entities/Attack.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Attack.cpp.s
.PHONY : entities/Attack.cpp.s

entities/Nexus.o: entities/Nexus.cpp.o
.PHONY : entities/Nexus.o

# target to build an object file
entities/Nexus.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Nexus.cpp.o
.PHONY : entities/Nexus.cpp.o

entities/Nexus.i: entities/Nexus.cpp.i
.PHONY : entities/Nexus.i

# target to preprocess a source file
entities/Nexus.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Nexus.cpp.i
.PHONY : entities/Nexus.cpp.i

entities/Nexus.s: entities/Nexus.cpp.s
.PHONY : entities/Nexus.s

# target to generate assembly for a file
entities/Nexus.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Nexus.cpp.s
.PHONY : entities/Nexus.cpp.s

entities/Unit.o: entities/Unit.cpp.o
.PHONY : entities/Unit.o

# target to build an object file
entities/Unit.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Unit.cpp.o
.PHONY : entities/Unit.cpp.o

entities/Unit.i: entities/Unit.cpp.i
.PHONY : entities/Unit.i

# target to preprocess a source file
entities/Unit.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Unit.cpp.i
.PHONY : entities/Unit.cpp.i

entities/Unit.s: entities/Unit.cpp.s
.PHONY : entities/Unit.s

# target to generate assembly for a file
entities/Unit.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Unit.cpp.s
.PHONY : entities/Unit.cpp.s

entities/Wall.o: entities/Wall.cpp.o
.PHONY : entities/Wall.o

# target to build an object file
entities/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Wall.cpp.o
.PHONY : entities/Wall.cpp.o

entities/Wall.i: entities/Wall.cpp.i
.PHONY : entities/Wall.i

# target to preprocess a source file
entities/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Wall.cpp.i
.PHONY : entities/Wall.cpp.i

entities/Wall.s: entities/Wall.cpp.s
.PHONY : entities/Wall.s

# target to generate assembly for a file
entities/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/AET.dir/build.make CMakeFiles/AET.dir/entities/Wall.cpp.s
.PHONY : entities/Wall.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... AET"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Body.o"
	@echo "... Body.i"
	@echo "... Body.s"
	@echo "... Engine.o"
	@echo "... Engine.i"
	@echo "... Engine.s"
	@echo "... Engine_Event.o"
	@echo "... Engine_Event.i"
	@echo "... Engine_Event.s"
	@echo "... Engine_Level.o"
	@echo "... Engine_Level.i"
	@echo "... Engine_Level.s"
	@echo "... Engine_Resources.o"
	@echo "... Engine_Resources.i"
	@echo "... Engine_Resources.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... Event.o"
	@echo "... Event.i"
	@echo "... Event.s"
	@echo "... Eye.o"
	@echo "... Eye.i"
	@echo "... Eye.s"
	@echo "... Fang.o"
	@echo "... Fang.i"
	@echo "... Fang.s"
	@echo "... Leg.o"
	@echo "... Leg.i"
	@echo "... Leg.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... entities/Attack.o"
	@echo "... entities/Attack.i"
	@echo "... entities/Attack.s"
	@echo "... entities/Nexus.o"
	@echo "... entities/Nexus.i"
	@echo "... entities/Nexus.s"
	@echo "... entities/Unit.o"
	@echo "... entities/Unit.i"
	@echo "... entities/Unit.s"
	@echo "... entities/Wall.o"
	@echo "... entities/Wall.i"
	@echo "... entities/Wall.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

